name: blog_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  #Functional programming in Dart and Flutter. All the main functional programming types and patterns fully documented, tested, and with examples.
  fpdart: ^1.1.0
  # Flutter integration for Supabase. This package makes it simple for developers to build secure and scalable products.
  supabase_flutter: ^2.5.8
  # Flutter bloc for state management.
  flutter_bloc: ^8.1.6
  # GetIt for dependency injection.
  get_it: ^7.7.0
  # Dotted border for creating a border around a widget.
  dotted_border: ^2.1.0
  # Image picker for picking image from gallery or camera.
  image_picker: ^1.1.2
  # UUID for generating unique IDs.
  uuid: ^4.4.2
  # Flutter internationalization.
  intl:


  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true